### ISSUE TITLE
Build fails on clout route compile

### ISSUE THREAD

**Issue by AlBaker** [weavejester/compojure#122]
Tried upgrading an app with compojure 1.1.6 to 1.2.0 and 'lein ring server' fails with:

```
Caused by: java.lang.NoSuchMethodError: clout.core.CompiledRoute.<init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
    at clout.core$route_compile.invoke(core.clj:95)
    at clout.core$route_compile.invoke(core.clj:85)
    at ring.middleware.refresh__init.load(Unknown Source)
    at ring.middleware.refresh__init.<clinit>(Unknown Source)
```

Tried adding the cloud 2.0 dependency directly, made sure all lein/ring stuff was up to date - no dice.

Anything I'm missing?

**Comment by leblowl** [comment]
I also received this error while using boot-clj/boot & packaging my app as an uberjar. It looks like unpacking one of my dependencies overwrites my compiled clout files. Problem is described here as well: http://stackoverflow.com/questions/31129470/java-lang-illegalargumentexception-no-implementation-of-method-route-matches/31569119#31569119.

Excluding compiled clout files in my uberjar task solves the problem.
