### ISSUE TITLE
Method missing in slf4j

### ISSUE THREAD

**Issue by lukesutton** [weavejester/compojure#79]
I'm using Leiningen 2.1.2, Clojure 1.4.0 and Compojure 1.1.5 on OS X 10.8. 

java -version gives me:

```
Java version "1.6.0_43"
Java(TM) SE Runtime Environment (build 1.6.0_43-b01-447-11M4203)
Java HotSpot(TM) 64-Bit Server VM (build 20.14-b01-447, mixed mode)
```

As a test, I've tried to generate a fresh Compojure app.

``` zsh
$ lein new compojure derp
$ cd derp
$ lein ring server
```

I get a stack trace like this

``` zsh
Exception in thread "main" java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
    at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:613)
    at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:200)
    at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:94)
    at org.eclipse.jetty.util.component.Container.add(Container.java:201)
    at org.eclipse.jetty.util.component.Container.update(Container.java:164)
    at org.eclipse.jetty.util.component.Container.update(Container.java:106)
    at org.eclipse.jetty.server.Server.setConnectors(Server.java:184)
    at org.eclipse.jetty.server.Server.addConnector(Server.java:158)
    at ring.adapter.jetty$create_server.invoke(jetty.clj:54)
    at ring.adapter.jetty$run_jetty.invoke(jetty.clj:79)
    at ring.server.standalone$serve$fn__1559.invoke(standalone.clj:98)
    at ring.server.standalone$try_port.invoke(standalone.clj:16)
    at ring.server.standalone$serve.doInvoke(standalone.clj:95)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at ring.server.leiningen$serve.invoke(leiningen.clj:20)
    at user$eval2122.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Subprocess failed
```

Now, I'm a nub and I might be missing something obvious, but I don't know how to debug this. To me, it feels like some sort of dependency conflict.

**Comment by duffyhart** [comment]
Thanks for the advice, it solved my problem too. I had a couple of JAR files in /usr/local/xuggler/share/java/jars due to upgrading a very old OS X system.  Deleting these fixed this issue.
